name: flutte_pokedex
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  flip_card: ^0.4.4
  flutter_dialogflow: ^0.1.3
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # scoped_model: ^1.0.1
  http: ^0.12.0+2
  carousel_slider: ^1.3.0
  sliding_up_panel:
  provider: 
  # shared_preferences: 
  flutter_advanced_networkimage: ^0.6.0-alpha.1
  # cached_network_image:
  flutter_tts: ^0.6.0
  flutter_svg: ^0.17.3+1
  firebase_auth: ^0.14.0+5
  rxdart: ^0.22.0
  shared_preferences:

dev_dependencies:
  flutter_launcher_icons: ^0.7.2+1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/pokeball_1.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pokeapp-c069a-ba559b7f2350.json
    - assets/json/pokemonJson.txt
    - assets/images/splash_2.jpg
    - assets/images/dotted.png
    - assets/images/pokeball.png
    - assets/images/pokeball_1.png
    - assets/images/pokimon_1.png
    - assets/images/pokimon_2.png
    - assets/images/pokimon_3.png
    - assets/images/pokimon_4.png
    - assets/images/pokimon_5.png
    - assets/images/pokimon_6.png
    - assets/images/pokimon_7.png
    - assets/images/pokimon_8.png
    - assets/images/pokimon_9.png
    - assets/images/pokimon_10.png
    - assets/images/pokimon_11.png
    - assets/images/pokimon_12.png
    - assets/images/pokimon_13.png
    - assets/images/pokimon_14.png
    - assets/images/pokimon_15.png
    - assets/images/pokimon_16.png
    - assets/images/pokimon_17.png
    - assets/images/pokimon_18.png
    - assets/images/pokimon_19.png
    - assets/images/pokimon_20.png
    - assets/images/pokimon_21.png
    - assets/images/pokimon_22.png
    - assets/images/pokimon_23.png
    - assets/images/pokimon_24.png
    - assets/images/pokimon_25.png
    - assets/images/pokimon_26.png
    - assets/images/pokimon_27.png
    - assets/images/types/Bug.png
    - assets/images/types/Dark.png
    - assets/images/types/Dragon.png
    - assets/images/types/Electric.png
    - assets/images/types/Fairy.png
    - assets/images/types/Fight.png
    - assets/images/types/Fire.png
    - assets/images/types/Flying.png
    - assets/images/types/Ghost.png
    - assets/images/types/Grass.png
    - assets/images/types/Ground.png
    - assets/images/types/Ice.png
    - assets/images/types/Normal.png
    - assets/images/types/Poison.png
    - assets/images/types/Psychic.png
    - assets/images/types/Rock.png
    - assets/images/types/Steel.png
    - assets/images/types/Water.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
